### ISSUE TITLE
`repeat`?

### ISSUE THREAD

**Issue by nanodeath** [czyzby/kotlin-times#3]
You enumerate plenty of possible equivalent in the README, but left out a pretty important one: [`repeat`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html). Not sure if that was on purpose or not.

**Comment by czyzby** [comment]
And `for(i in 0 until n)`. Yes, I missed some equivalents when writing the README, but - as you can guess - this is more of a joke than an actual library. `repeat` does seem like the closest thing to `times` functions.

**Comment by nanodeath** [comment]
> more of a joke than an actual library

I was only 2/3 sure that was the case 😉
